freebsd_instance:
  image_family: freebsd-12-2

env:
  TESTS_REDUCED_KEYLENGTHS: yes
  LEAK_DETECTIVE: no
  MONOLITHIC: no
  TEST: freebsd
  OS_NAME: freebsd

task:
  install_script: ./scripts/test.sh deps
  script: ./scripts/test.sh
