task:
  matrix:
    - name: FreeBSD 13.2
      freebsd_instance:
        image_family: freebsd-13-2
    - name: FreeBSD 12.4
      freebsd_instance:
        image_family: freebsd-12-4

  env:
    TESTS_REDUCED_KEYLENGTHS: yes
    LEAK_DETECTIVE: no
    MONOLITHIC: no
    TEST: freebsd
    OS_NAME: freebsd

  install_script: ./scripts/test.sh deps
  script: ./scripts/test.sh
